.TH "oxy-serve-one" 1
.SH NAME
oxy-serve-one
.SH SYNOPSIS
oxy serve-one [-hipVv] <bind-address>
.SH DESCRIPTION
Accept a single TCP connection, then service it in the same process.
.PP
--client-config <client config>

.RS
Path to client.conf [default: ~/.config/oxy/client.conf]
.RE

--forced-command <forced command>

.RS
Restrict command execution to the specified command
.RE

-h, --help

.RS
Prints help information
.RE

-i, --identity <identity>

.RS
Use [identity] as authentication information for connecting to the remote
.RE
.RS
server. [env: OXY_IDENTITY=]
.RE

-p, --port <port>

.RS
The port used for TCP [default: 2600]
.RE

--server-config <server config>

.RS
Path to server.conf [default: ~/.config/oxy/server.conf]
.RE

-V, --version

.RS
Prints version information
.RE

-v, --verbose

.RS
Increase debugging output
.RE


.SH AUTHOR
Jenna Magius <pyrosim@gmail.com>
